version: '3.9'

services:
  mongo:
    image: mongo:7.0.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      ONGO_INITDB_DATABASE: evilton-fleet-management

volumes:
  mongo-data: